config/urls.py
"""Base URL settings for the Study Buffalo website."""
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.contrib.sitemaps.views import sitemap

from supporting import views
from supporting.sitemaps import PlaySitemap, StudySitemap, ToolSitemap, ReadSitemap, StaticViewSitemap


sitemaps = {
    'play': PlaySitemap('play'),
    'study': StudySitemap('study'),
    'tools': ToolSitemap('tools'),
    'read': ReadSitemap('read'),
    'static': StaticViewSitemap('other'),
}

urlpatterns = [
    path('api/', include('study_buffalo.api.urls', namespace='api')),
    path('play/', include('play.urls')),
    path('study/', include('study.urls')),
    path('read/', include('read.urls')),
    path('tools/', views.tools_index, name='tools_index'),
    path('rdrhc-calendar/', include('rdrhc_calendar.urls', namespace='rdrhc_calendar')),
    path('tools/alberta-adaptations/', views.alberta_adaptations_index, name='alberta_adaptations_index'),
    path('tools/dictionary/', include('dictionary.urls')),
    path('tools/dpd/', include('hc_dpd.urls', namespace='hc_dpd')),
    path('tools/drug-price-calculator/', include('drug_price_calculator.urls')),
    path('tools/substitutions/', include('substitutions.urls')),
    path('tools/vancomycin-calculator/', include('vancomycin_calculator.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('design/', views.design_index, name='design_index'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('robot-policy/', views.robot_policy, name='robot_policy'),
    path('contact/', views.contact, name='contact'),
    path(
        'sitemap/',
        views.custom_sitemap,
        {'sitemaps': sitemaps, 'template_name': 'sitemap_template.html', 'content_type': None},
        name='sitemap'
    ),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('unsubscribe/', views.unsubscribe, name='unsubscribe'),
    path('unsubscribe/complete/', views.unsubscribe_complete, name='unsubscribe_complete'),
    path('accounts/profile/', views.account_profile, name='account_profile'),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt'), name='robots.txt'),
    path('', views.Index.as_view(), name='index'),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TEMPORARY URLS & REDIRECTS
urlpatterns += [
    path('cabs2018/', TemplateView.as_view(template_name='pages/cabs2018.html'), name='cabs2018'),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            '400/',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')},
        ),
        path(
            '403/',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')},
        ),
        path(
            '404/',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')},
        ),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

sb_django/urls.py
"""
Definition of urls for sb_django.
"""
from django.conf.urls import url
import django.contrib.auth.views

from django.conf.urls import include
from django.contrib import admin
from django.views.generic import RedirectView
from . import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from .sitemaps import *

import environ

# Dictionary containing your sitemap classes
sitemaps = {
   "play": PlaySitemap("play"),
   "study": StudySitemap("study"),
   "tools": ToolSitemap("tools"),
   "read": ReadSitemap("read"),
   "static": StaticViewSitemap("other"),
}

urlpatterns = [
    url(r"^play/", include("play.urls")),
    url(r"^study/", include("study.urls")),
    url(r"^read/", include("read.urls")),
    url(r"^tools/$", views.tools_index, name="tools_index"),
    url(r"^tools/alberta-adaptations/", views.alberta_adaptations_index, name="alberta_adaptations_index"),
    url(r"^tools/drug-price-calculator/", include("drug_price_calculator.urls")),
    url(r"^tools/vancomycin-calculator/", include("vancomycin_calculator.urls")),
    url(r"^design/$", views.design_index, name="design_index"),
    url(r"^privacy-policy/", views.privacy_policy, name="privacy_policy"),
    url(r"^robot-policy/", views.robot_policy, name="robot_policy"),
    url(r"^contact/", views.contact, name="contact"),
    url(r"^sitemap/", views.custom_sitemap, {"sitemaps": sitemaps, "template_name": "sitemap_template.html", "content_type": None}, name="sitemap"),
    url(r"^sitemap\.xml$", sitemap, {"sitemaps": sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r"^accounts/profile/$", views.account_profile, name="account_profile"),
    url(r"^accounts/", include("allauth.urls")),
    url(r"^$", views.Index.as_view(), name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Set a secure path for the admin site
# Set the Base Directory
BASE_DIR = environ.Path(__file__) - 2

# Connect to the .env file
env = environ.Env(DEBUG=(bool, False),)
environ.Env.read_env(env_file=BASE_DIR.path('..', 'config').file('studybuffalo.env'))

admin_regex = r"%s" % env('ADMIN_URL')

urlpatterns += [
    url(admin_regex, include(admin.site.urls)),
]

study_buffalo/api/rdrhc_calendar/urls.py
"""URLs for the RDRHC Calendar API."""
from django.conf.urls import include
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from api.rdrhc_calendar import views

app_name = 'api_v1'
urlpatterns = [
    path('authentication/', include('rest_framework.urls', namespace='rest_framework')),
    path('users/', views.UserList.as_view(), name='user_list'),
    path('users/<int:user_id>/', views.UserDetail.as_view(), name='user_detail'),
    path('users/<int:user_id>/emails/', views.UserEmailList.as_view(), name='user_email_list'),
    path('users/<int:user_id>/emails/first-sent/', views.UserEmailFirstSent.as_view(), name='user_email_first_sent'),
    path('shifts/', views.ShiftList.as_view(), name='shift_list'),
    path('shifts/<int:user_id>/', views.UserScheduleList.as_view(), name='user_schedule_list'),
    path('shifts/<int:user_id>/delete/', views.UserScheduleDelete.as_view(), name='user_schedule_delete'),
    path('shifts/<int:user_id>/upload/', views.UserScheduleUpload.as_view(), name='user_schedule_upload'),
    path('shift-codes/<int:user_id>/', views.UserShiftCodesList.as_view(), name='user_shift_codes_list'),
    path('shift-codes/missing/upload/', views.MissingShiftCodesUpload.as_view(), name='missing_shift_codes_upload'),
    path('stat-holidays/', views.StatHolidaysList.as_view(), name='stat_holidays_list'),
    path('', views.api_root, name='root'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

study_buffalo/rdrhc_calendar/urls.py
"""URLs for the RDRHC Calendar app."""
from django.urls import path

from . import views


app_name = 'rdrhc_calendar'

urlpatterns = [
    path('settings/', views.calendar_settings, name='settings'),
    path('shifts/', views.ShiftCodeList.as_view(), name='code_list'),
    path('shifts/<int:code_id>/', views.calendar_code_edit, name='code_edit'),
    path('shifts/add/', views.calendar_code_add, name='code_add'),
    path('shifts/delete/<int:code_id>/', views.calendar_code_delete, name='code_delete'),
    path('missing-codes/', views.MissingShiftCodeList.as_view(), name='missing_code_list'),
    path('missing-codes/edit/<int:code_id>/', views.missing_code_edit, name='missing_code_edit'),
    path('missing-codes/delete/<int:code_id>/', views.missing_code_delete, name='missing_code_delete'),
    path('', views.calendar_index, name='index'),
]

study_buffalo/api/rdrhc_calendar/views.py
"""Views for the RDRHC Calendar API."""
from datetime import datetime

from django.contrib.auth import get_user_model
from django.db import DataError
from django.db.models import Q
from django.shortcuts import get_object_or_404

from allauth.account.models import EmailAddress
from rest_framework.authentication import SessionAuthentication, TokenAuthentication
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework.views import APIView
from rest_framework import generics, status

from rdrhc_calendar import models
from api.rdrhc_calendar import serializers
from api.rdrhc_calendar.permissions import HasAPIAccess


@api_view(['GET'])
@authentication_classes((SessionAuthentication, TokenAuthentication, ))
@permission_classes((IsAuthenticated, HasAPIAccess, ))
def api_root(request, format=None):  # pylint: disable=redefined-builtin
    """Top-level view for the RDRHC Calendar API."""
    return Response({
        'users': reverse('api:rdrhc_calendar_v1:user_list', request=request, format=format),
        'shifts': reverse('api:rdrhc_calendar_v1:shift_list', request=request, format=format),
    })


class UserList(generics.ListAPIView):
    """List view of all RDRHC Calendar users."""
    queryset = models.CalendarUser.objects.all().order_by('role', 'name',)
    authentication_classes = (SessionAuthentication, TokenAuthentication, )
    permission_classes = (IsAuthenticated, HasAPIAccess, )
    serializer_class = serializers.UserSerializer


class UserDetail(generics.RetrieveUpdateDestroyAPIView):
    """Detail view of a RDRHC Calendar user."""
    queryset = models.CalendarUser.objects.all()
    authentication_classes = (SessionAuthentication, TokenAuthentication, )
    permission_classes = (IsAuthenticated, HasAPIAccess, )
    serializer_class = serializers.UserSerializer
    lookup_field = 'id'
    lookup_url_kwarg = 'user_id'


class UserEmailList(generics.ListAPIView):
    """List view of a RDRHC Calendar user's emails."""
    authentication_classes = (SessionAuthentication, TokenAuthentication, )
    permission_classes = (IsAuthenticated, HasAPIAccess, )
    serializer_class = serializers.EmailSerializer

    def get_queryset(self):
        user_id = self.kwargs.get('user_id', None)
        user = get_user_model().objects.get(id=user_id)

        emails = EmailAddress.objects.filter(user=user)

        return emails

    def list(self, request, *args, **kwargs):
        return Response(self.get_queryset().values_list('email', flat=True))


class ShiftList(generics.ListAPIView):
    """List view of the RDRHC Calendar shifts."""
    queryset = models.Shift.objects.all()
    authentication_classes = (SessionAuthentication, TokenAuthentication, )
    permission_classes = (IsAuthenticated, HasAPIAccess, )
    serializer_class = serializers.ShiftSerializer


class UserShiftCodesList(generics.ListAPIView):
    """List view of a user's RDRHC Calendar shifts."""
    authentication_classes = (SessionAuthentication, TokenAuthentication, )
    permission_classes = (IsAuthenticated, HasAPIAccess, )
    serializer_class = serializers.ShiftCodesSerializer

    def get_queryset(self):
        # Get a reference to the main user model
        user_id = self.kwargs.get('user_id', None)
        user = get_user_model().objects.get(id=user_id)

        # Collect the user-specific codes
        user_codes = models.ShiftCode.objects.filter(sb_user=user)

        # Collect the default codes (i.e. no user)
        default_codes = models.ShiftCode.objects.filter(
            Q(role=user.calendar_user.role) & Q(sb_user__isnull=True)
        )

        # Add all the user_codes into the codes list
        codes = []

        for u_code in user_codes:
            codes.append(u_code)

        # Add any default codes that don't have a user code already
        for d_code in default_codes:
            if not any(d_code.code == code.code for code in codes):
                codes.append(d_code)

        return codes


class StatHolidaysList(generics.ListAPIView):
    """List view of the RDRHC Calendar statutory holidays."""
    authentication_classes = (SessionAuthentication, TokenAuthentication, )
    permission_classes = (IsAuthenticated, HasAPIAccess, )
    serializer_class = serializers.StatHolidaySerializer

    def get_queryset(self):
        date_start = self.request.GET.get('date_start', datetime(2001, 1, 1))
        date_end = self.request.GET.get('date_end', datetime(2025, 12, 31))

        queryset = models.StatHoliday.objects.all().filter(
            Q(date__gte=date_start) & Q(date__lte=date_end)
        )

        return queryset

    def list(self, request, *args, **kwargs):
        return Response(self.get_queryset().values_list('date', flat=True))


class UserScheduleList(generics.ListAPIView):
    """List view of a RDRHC Calendar user's schedule."""
    authentication_classes = (SessionAuthentication, TokenAuthentication, )
    permission_classes = (IsAuthenticated, HasAPIAccess, )
    serializer_class = serializers.ShiftSerializer

    def get_queryset(self):
        user_id = self.kwargs.get('user_id', None)

        queryset = models.Shift.objects.all().filter(
            sb_user=user_id
        ).order_by('date')

        return queryset


class UserScheduleDelete(APIView):
    """Delete view for a RDRHC Calendar user's schedule."""
    authentication_classes = (SessionAuthentication, TokenAuthentication, )
    permission_classes = (IsAuthenticated, HasAPIAccess, )

    def delete(self, request, user_id):
        """Deletes all shifts associated to the specified user."""
        shifts = models.Shift.objects.filter(sb_user=user_id)
        shifts.delete()

        return Response(status=status.HTTP_204_NO_CONTENT)


class UserScheduleUpload(APIView):
    """Create view for a RDRHC Calendar user's schedule."""
    authentication_classes = (SessionAuthentication, TokenAuthentication, )
    permission_classes = (IsAuthenticated, HasAPIAccess, )

    def post(self, request, user_id):
        """Adds all the shift codes for a user."""
        schedule = serializers.ShiftSerializer(
            data=request.data.get('schedule', []),
            many=True
        )

        if schedule.is_valid():
            schedule.save()

            response_message = (
                f'Schedule successfully uploaded for user id = {user_id}'
            )

            return Response(
                data={'message': response_message},
                status=status.HTTP_200_OK
            )

        return Response(
            data={
                'request_data': request.data.get('schedule'),
                'errors': schedule.errors,
            },
            status=status.HTTP_400_BAD_REQUEST
        )


class UserEmailFirstSent(APIView):
    """Update view to note welcome email sent to a new RDRHC Calendar user."""
    authentication_classes = (SessionAuthentication, TokenAuthentication, )
    permission_classes = (IsAuthenticated, HasAPIAccess, )

    def post(self, request, user_id):
        """Updates user profile to note that first email was sent."""
        calendar_user = get_object_or_404(models.CalendarUser, sb_user=user_id)
        calendar_user.first_email_sent = True
        calendar_user.save()

        return Response(status=status.HTTP_200_OK)


class MissingShiftCodesUpload(APIView):
    """Create view to upload missing shift codes."""
    authentication_classes = (SessionAuthentication, TokenAuthentication, )
    permission_classes = (IsAuthenticated, HasAPIAccess, )

    def post(self, request):
        """Creates new missing shift code entries."""
        codes = request.data.get('codes', [])

        new_codes = []

        for code in codes:
            try:
                db_code, created = models.MissingShiftCode.objects.get_or_create(
                    code=code['code'], role=code['role']
                )

                if created:
                    new_codes.append(db_code.code)
            except (DataError, KeyError, TypeError) as e:
                return Response(
                    data=str(e),
                    status=status.HTTP_400_BAD_REQUEST,
                )

        return Response(
            data=new_codes,
            status=status.HTTP_200_OK,
        )

study_buffalo/rdrhc_calendar/templates/rdrhc_calendar/calendar_settings.html
{% extends "base_generic.html" %}

{% block styles %}
{% endblock %}

{% load static %}

{% block content %}
	<h1><a href="{% url 'rdrhc_calendar:index' %}">RDRHC Calendar</a> &gt; Settings</h1>

	<p>
		You may modify the following details of your schedule. Please note that
		the changes may take up to 24 hours to take effect.
	</p>

	<form action="" method="post">
		{% csrf_token %}

		{% if messages or form.errors or form.non_field_errors %}
			<ul class="message_list">
				{% for message in messages %}
					{% if message.level %}
						<li class="level_{{ message.level }}">{{ message }}</li>
					{% else %}
						<li>{{ message }}</li>
					{% endif %}
				{% endfor %}
			</ul>
		{% endif %}

		<h2>Calendar Name</h2>

		<ul class="message_list">
			{% for error in form.calendar_name.errors %}
				<li class="level_40">{{ error|striptags }}</li>
			{% endfor %}
		</ul>

		<p>
			<strong>{{ form.calendar_name.help_text }}</strong><br>
			<label for="{{ form.calendar_name.id_for_label}}">
				Calendar Name:
			</label>
			{{ form.calendar_name }}
		</p>

		<h2>Full Day Shifts</h2>

		<ul class="message_list">
			{% for error in form.full_day.errors %}
				<li class="level_40">{{ error|striptags }}</li>
			{% endfor %}
		</ul>

		<p>
			<strong>{{ form.full_day.help_text }}</strong><br>
			<label for="{{ form.full_day.id_for_label}}">
				Full Day Shift:
			</label>
			{{ form.full_day }}
		</p>

		<h2>Shift Reminders</h2>

		<ul class="message_list">
			{% for error in form.reminder.errors %}
				<li class="level_40">{{ error|striptags }}</li>
			{% endfor %}
		</ul>

		<p>
			<strong>{{ form.reminder.help_text }}</strong><br>
			<label for="{{ form.reminder.id_for_label}}">
				Reminder:
			</label>
			{{ form.reminder }} minutes
		</p>

		<button type="submit" name="action">Update Settings</button>
	</form>
{% endblock %}

study_buffalo/rdrhc_calendar/templates/rdrhc_calendar/missingshiftcode_delete.html
{% extends "base_generic.html" %}

{% block styles %}
	<style>
		#sb .center_content table td, #sb .center_content table th {
			padding: 1rem;
		}

		#sb .center_content table thead th,
		#sb .center_content table tbody td {
			text-align: center;
		}

		#sb .center_content table tfoot td {
			text-align: right;
		}
	</style>
{% endblock %}

{% load static %}

{% block content %}
	<h1>
		<a href="{% url 'rdrhc_calendar:index' %}">RDRHC Calendar</a> &gt;
		<a href="{% url 'rdrhc_calendar:missing_code_list' %}">Missing Shift Codes</a> &gt;
		Delete Shift Code
	</h1>

	<form action="" method="post">
		{% csrf_token %}

		<div class="center_content">
			<table>
				<thead>
					<tr>
						<th>Are you sure you want to delete this shift code:</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>{{ shift_code }}</td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<td><button type="submit">Delete</button></td>
					</tr>
				</tfoot>
			</table>
		</div>
	</form>
{% endblock %}

study_buffalo/rdrhc_calendar/templates/rdrhc_calendar/missingshiftcode_list.html
{% extends "base_generic.html" %}

{% block styles %}
	<style>
		#sb #code_list {
			display: flex;
			flex-direction: column;
			justify-content: center;
			width: 100%;
		}

		#sb #code_list > div {
			display: flex;
			flex-direction: row;
			justify-content: center;
			transition: ease-in-out 0.4s;
			width: 100%;
		}
			#sb #code_list > div.code_row {
				padding: 0.5rem 0;
			}

				#sb #code_list > div.code_row:nth-child(even) {
					background-color: rgb(240, 240, 240);
				}

				#sb #code_list > div.code_row:hover {
					background-color: rgb(200, 200, 200);
				}

			#sb #code_list > div .role {
				flex: 1 1 75px;
				max-width: 150px;
			}

				#sb #code_list > div a.role {
					color: inherit;
					text-decoration: none;
				}

			#sb #code_list > div .shift {
				flex: 1 1 125px;
				max-width: 150px;
			}

				#sb #code_list > div a.shift {
					color: inherit;
					text-decoration: none;
				}

			#sb #code_list > div .delete {
				flex: 1 1 125px;
				max-width: 150px;
			}

				#sb #code_list > div a.delete {
					font-weight: 700;
					text-decoration: none;
				}
	</style>
{% endblock %}

{% load static %}

{% block content %}
	<h1><a href="{% url 'rdrhc_calendar:index' %}">RDRHC Calendar</a> &gt; Missing Shift Codes</h1>

	{% if messages %}
		<ul class="message_list">
			{% for message in messages %}
				{% if message.level %}
					<li class="level_{{ message.level }}">{{ message }}</li>
				{% else %}
					<li>{{ message }}</li>
				{% endif %}
			{% endfor %}
		</ul>
	{% endif %}

	<p>
		Click on the shift code below to sets its default start and stop times
	</p>

	{% if shift_code_list %}
		<div id="code_list">
			<div>
				<strong class="role">Role</strong>
				<strong class="shift">Shift Code</strong>
				<strong class="delete"></strong>
			</div>
			{% for code in shift_code_list %}
				<div class="code_row">
					<a href="{% url 'rdrhc_calendar:missing_code_edit' code.id %}" class="role">
						{{ code.role }}
					</a>
					<a href="{% url 'rdrhc_calendar:missing_code_edit' code.id %}" class="shift">
						{{ code.code }}
					</a>
					<a href="{% url 'rdrhc_calendar:missing_code_delete' code.id %}" class="delete">
						Delete
					</a>
				</div>
			{% endfor %}
		</div>
	{% endif %}
{% endblock %}

study_buffalo/rdrhc_calendar/templates/rdrhc_calendar/shiftcode_delete.html
{% extends "base_generic.html" %}

{% block styles %}
	<style>
		#sb .center_content table td, #sb .center_content table th {
			padding: 1rem;
		}

		#sb .center_content table thead th,
		#sb .center_content table tbody td {
			text-align: center;
		}

		#sb .center_content table tfoot td {
			text-align: right;
		}
	</style>
{% endblock %}

{% load static %}

{% block content %}
	<h1>
		<a href="{% url 'rdrhc_calendar:index' %}">RDRHC Calendar</a> &gt;
		<a href="{% url 'rdrhc_calendar:code_list' %}">Custom Shift Codes</a> &gt;
		Delete Shift Code
	</h1>

	<form action="" method="post">
		{% csrf_token %}

		<div class="center_content">
			<table>
				<thead>
					<tr>
						<th>Are you sure you want to delete this shift code:</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>{{ shift_code }}</td>
					</tr>
				</tbody>
				<tfoot>
					<tr>
						<td><button type="submit">Delete</button></td>
					</tr>
				</tfoot>
			</table>
		</div>
	</form>
{% endblock %}

study_buffalo/rdrhc_calendar/templates/rdrhc_calendar/shiftcode_list.html
{% extends "base_generic.html" %}

{% block styles %}
	<style>
		#sb .center_content {
			margin: 2rem 0;
		}

		#sb #code_list {
			border-collapse: collapse;
		}

		#sb #code_list td {
			border: 1px solid rgb(50, 50, 50);
			text-align: center;
		}

			#sb #code_list td a {
				display: block;
				padding: 1rem;
				transition: ease-in-out 0.3s;
			}

			#sb #code_list td a:hover {
				background-color: rgb(200, 200, 200);
				display: block;
			}

		#sb #code_list tr td:first-child {
			font-weight: 700;
			width: 15rem;
		}

		#sb #code_list a {
			color: inherit;
			text-decoration: none;
		}
	</style>
{% endblock %}

{% load static %}

{% block content %}
	<h1><a href="{% url 'rdrhc_calendar:index' %}">RDRHC Calendar</a> &gt; Custom Shift Codes</h1>

	{% if messages %}
		<ul class="message_list">
			{% for message in messages %}
				{% if message.level %}
					<li class="level_{{ message.level }}">{{ message }}</li>
				{% else %}
					<li>{{ message }}</li>
				{% endif %}
			{% endfor %}
		</ul>
	{% endif %}

	<div class="center_content">
		<a href="{% url 'rdrhc_calendar:code_add' %}">Click here to add a new shift code</a>
	</div>

	{% if shift_code_list %}
		<div class="center_content">
			Click on the shift code below to edit its start and stop times
		</div>

		<div class="center_content">
			<table id="code_list">
				{% for code in shift_code_list %}

					<tr>
						<td>
							<a href="{% url 'rdrhc_calendar:code_edit' code.id %}">
								{{ code.code }}
							</a>
						</td>
						<td>
							<a href="{% url 'rdrhc_calendar:code_delete' code.id %}">
								Delete
							</a>
						</td>
					</tr>
				{% endfor %}
			</table>
		</div>
	{% endif %}
{% endblock %}