config/urls.py
"""Base URL settings for the Study Buffalo website."""
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.contrib.sitemaps.views import sitemap

from supporting import views
from supporting.sitemaps import PlaySitemap, StudySitemap, ToolSitemap, ReadSitemap, StaticViewSitemap


sitemaps = {
    'play': PlaySitemap('play'),
    'study': StudySitemap('study'),
    'tools': ToolSitemap('tools'),
    'read': ReadSitemap('read'),
    'static': StaticViewSitemap('other'),
}

urlpatterns = [
    path('api/', include('study_buffalo.api.urls', namespace='api')),
    path('play/', include('play.urls')),
    path('study/', include('study.urls')),
    path('read/', include('read.urls')),
    path('tools/', views.tools_index, name='tools_index'),
    path('rdrhc-calendar/', include('rdrhc_calendar.urls', namespace='rdrhc_calendar')),
    path('tools/alberta-adaptations/', views.alberta_adaptations_index, name='alberta_adaptations_index'),
    path('tools/dictionary/', include('dictionary.urls')),
    path('tools/dpd/', include('hc_dpd.urls', namespace='hc_dpd')),
    path('tools/drug-price-calculator/', include('drug_price_calculator.urls')),
    path('tools/substitutions/', include('substitutions.urls')),
    path('tools/vancomycin-calculator/', include('vancomycin_calculator.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('design/', views.design_index, name='design_index'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('robot-policy/', views.robot_policy, name='robot_policy'),
    path('contact/', views.contact, name='contact'),
    path(
        'sitemap/',
        views.custom_sitemap,
        {'sitemaps': sitemaps, 'template_name': 'sitemap_template.html', 'content_type': None},
        name='sitemap'
    ),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('unsubscribe/', views.unsubscribe, name='unsubscribe'),
    path('unsubscribe/complete/', views.unsubscribe_complete, name='unsubscribe_complete'),
    path('accounts/profile/', views.account_profile, name='account_profile'),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt'), name='robots.txt'),
    path('', views.Index.as_view(), name='index'),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TEMPORARY URLS & REDIRECTS
urlpatterns += [
    path('cabs2018/', TemplateView.as_view(template_name='pages/cabs2018.html'), name='cabs2018'),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            '400/',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')},
        ),
        path(
            '403/',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')},
        ),
        path(
            '404/',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')},
        ),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

sb_django/urls.py
"""
Definition of urls for sb_django.
"""
from django.conf.urls import url
import django.contrib.auth.views

from django.conf.urls import include
from django.contrib import admin
from django.views.generic import RedirectView
from . import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from .sitemaps import *

import environ

# Dictionary containing your sitemap classes
sitemaps = {
   "play": PlaySitemap("play"),
   "study": StudySitemap("study"),
   "tools": ToolSitemap("tools"),
   "read": ReadSitemap("read"),
   "static": StaticViewSitemap("other"),
}

urlpatterns = [
    url(r"^play/", include("play.urls")),
    url(r"^study/", include("study.urls")),
    url(r"^read/", include("read.urls")),
    url(r"^tools/$", views.tools_index, name="tools_index"),
    url(r"^tools/alberta-adaptations/", views.alberta_adaptations_index, name="alberta_adaptations_index"),
    url(r"^tools/drug-price-calculator/", include("drug_price_calculator.urls")),
    url(r"^tools/vancomycin-calculator/", include("vancomycin_calculator.urls")),
    url(r"^design/$", views.design_index, name="design_index"),
    url(r"^privacy-policy/", views.privacy_policy, name="privacy_policy"),
    url(r"^robot-policy/", views.robot_policy, name="robot_policy"),
    url(r"^contact/", views.contact, name="contact"),
    url(r"^sitemap/", views.custom_sitemap, {"sitemaps": sitemaps, "template_name": "sitemap_template.html", "content_type": None}, name="sitemap"),
    url(r"^sitemap\.xml$", sitemap, {"sitemaps": sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r"^accounts/profile/$", views.account_profile, name="account_profile"),
    url(r"^accounts/", include("allauth.urls")),
    url(r"^$", views.Index.as_view(), name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Set a secure path for the admin site
# Set the Base Directory
BASE_DIR = environ.Path(__file__) - 2

# Connect to the .env file
env = environ.Env(DEBUG=(bool, False),)
environ.Env.read_env(env_file=BASE_DIR.path('..', 'config').file('studybuffalo.env'))

admin_regex = r"%s" % env('ADMIN_URL')

urlpatterns += [
    url(admin_regex, include(admin.site.urls)),
]

study_buffalo/study/urls.py
"""URLs for the Study app."""
from django.urls import path

from . import views

urlpatterns = [
    path('<int:pk>/', views.GuideDetail.as_view(), name='study_guide_page'),
    path('', views.Index.as_view(), name='study_index'),
]

study_buffalo/users/urls.py
"""URLs for the Users app."""
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
    path('', view=views.UserListView.as_view(), name='list'),
    path('~redirect/', view=views.UserRedirectView.as_view(), name='redirect'),
    path('~update/', view=views.UserUpdateView.as_view(), name='update'),
    path('<str:username>/', view=views.UserDetailView.as_view(), name='detail',),
]

study_buffalo/study/models.py
"""Models for the Study app."""
from django.db import models
from django.urls import reverse
from django.conf import settings


class Guide(models.Model):
    """Defines the main study guide model"""
    title = models.CharField(
        help_text='The title of the study guide',
        max_length=100,
    )
    short_description = models.CharField(
        help_text='A short description of the study guide',
        max_length=256,
    )
    long_description = models.TextField(
        blank=True,
        help_text='A longer description of the study guide; supports HTML',
        null=True,
    )
    date_original = models.DateField(
        help_text='The date the first version was released',
    )
    last_update = models.DateField(
        help_text='The date of the last update',
    )
    permissions = models.CharField(
        blank=True,
        choices=(('dsm', 'DSM Study Guide'),),
        help_text='If the study guide has any special permissions to access it',
        max_length=3,
        null=True,
    )

    class Meta:
        ordering = ['title']

    def __str__(self):
        return f'{self.title} (Updated {self.last_update})'

    def get_absolute_url(self):
        """Returns the URL to this page"""
        return reverse('study_guide_page', args=[str(self.id)])

    def has_bounty(self):
        """Returns if a Bounty is set or not."""
        return self.bounty_set.all().exists()


class Bounty(models.Model):
    """Defines a bounty on a study guide"""
    study_guide = models.ForeignKey(
        'Guide',
        on_delete=models.CASCADE,
    )
    bounty_status = models.CharField(
        choices=(('o', 'Open'), ('c', 'Completed'),),
        default='o',
        help_text='The status of the bounty',
        max_length=1,
    )
    bounty_amount = models.DecimalField(
        decimal_places=2,
        default=0,
        help_text='The amount to be awarded on completion of the bounty',
        max_digits=6,
    )
    bounty_details = models.TextField(
        help_text='The details of the bounty; supports HTML',
    )

    class Meta:
        ordering = ['study_guide', 'bounty_status']

    def __str__(self):
        return f'${self.bounty_amount} bounty on {self.study_guide}'


class BountyAssignment(models.Model):
    """Defines the assignment of a user to a bounty"""
    bounty = models.ForeignKey(
        'Bounty',
        on_delete=models.CASCADE
    )
    assignment_status = models.CharField(
        choices=(('i', 'In progress'), ('r', 'Rewarded')),
        help_text='The current status of the user\'s work on the bounty',
        max_length=1,
    )
    assigned_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        help_text='The user assigned to this bounty',
        on_delete=models.CASCADE,
    )
    proportion = models.DecimalField(
        decimal_places=2,
        default=0,
        help_text='The proprtion of the bounty award the user received',
        max_digits=3,
    )

    class Meta:
        ordering = ['bounty', 'proportion', 'assigned_user']

    def __str__(self):
        return f'{self.bounty} assigned to {self.assigned_user}'


class HTMLGuide(models.Model):
    """Defines an HTML study guide"""
    study_guide = models.ForeignKey(
        'Guide',
        on_delete=models.CASCADE,
    )
    html = models.TextField(
        help_text='The HTML content to display the guide'
    )

    def __str__(self):
        return f'HTML for {self.study_guide}'


class DocumentGuide(models.Model):
    """Defines a document study guide"""
    study_guide = models.ForeignKey(
        'Guide',
        on_delete=models.CASCADE,
    )
    document = models.FileField(
        help_text='The study guide file to upload (PDF preferred)',
        upload_to='study_guides',
    )

    def __str__(self):
        return f'Document for {self.study_guide}'

study_buffalo/study/views.py
"""Views for the Study app."""
from django.views import generic
from .models import Guide


class Index(generic.ListView):
    """Index view for the Study app."""
    model = Guide
    context_object_name = 'guide_list'
    template_name = 'study/index.html'


class GuideDetail(generic.DetailView):
    """Detail view for a Guide."""
    model = Guide

    context_object_name = 'guide_page'

study_buffalo/study/templates/study/guide_detail.html
{% extends "base_generic.html" %}

{% load static %}

{% block content %}
	{% if guide_page %}
		<h1><a href="{% url 'study_index' %}">Study</a> &gt; {{ guide_page.title }}</h1>
		
		<p>
			<strong>Last Update:</strong> 
			{{ guide_page.last_update|date:"Y.m.d" }}
		</p>
		
		{% for item in guide_page.htmlguide_set.all %}
			<div>{{ item.html|safe }}</div>
		{% endfor %}

		{% for item in guide_page.documentguide_set.all %}
			<div class="embedded_pdf">
				<object data="{{ item.document.url }}" type="application/pdf">
					<a href="{{ item.document.url }}" target="_blank">
						Sorry, your browser cannot display the Study Guide - 
						click here to download it
					</a>
				</object>
			</div>
			
			<div class="center_content">
				<a href="{{ item.document.url }}" target="_blank">
					Click here to open this in a new window
				</a>
			</div>
		{% endfor %}
	{% endif %}
{% endblock %}

study_buffalo/study/templates/study/index.html
{% extends "base_generic.html" %}

{% block styles %}
	<style>
		#sb main {
			display: flex;
			flex-direction: column;
			justify-content: center;
			padding: 0;
			margin: 0;
		}

			#sb main .guide {
				border: 2px solid rgb(101, 101, 101);
				display: block;
				margin: 1rem 0.2rem;
				transition: 0.25s ease-in-out;
				width: 100%;
			}

				#sb main .guide:hover {
					border: 2px solid rgb(41, 138, 0);
				}

					#sb main .guide:hover h2 {
						background-color: rgb(41, 138, 0);
					}

				#sb main .guide a {
					color: inherit;
					display: block;
					text-decoration: none;
				}

				#sb main .guide h2 {
					background-color: rgb(31, 103, 0);
					color: rgb(250, 250, 250);
					display: block;
					padding: 2rem 1rem;
					margin: 0;
					transition: 0.25s ease-in-out;
				}

				#sb main .guide h2::after {
					content: none;
				}

				#sb main .guide div {
					padding: 2rem;
				}

				#sb main .guide ul {
					background-color: rgb(50, 50, 50);
					color: rgb(250, 250, 250);
					display: flex;
					flex-direction: row;
					font-size: 1.6rem;
					justify-content: space-between;
					padding: 0.25rem;
					margin: 0;
					flex-wrap: wrap;
				}

				#sb main .guide li {
					display: inline-block;
					line-height: 2rem;
					list-style: none;
					padding: 0 2rem;
				}
	</style>
{% endblock %}

{% load static %}

{% block content %}
	<h1>Study</h1>

	<main>
		{% if guide_list %}
			{% for guide in guide_list %}
				<div class="guide">
					<a href="{% url 'study_guide_page' guide.pk %}">
						<h2>{{ guide.title }}</h2>

						<div>{{ guide.short_description }}</div>

						<ul>
							<li>
								<i>
									Originally released on {{ guide.date_original }}<br>
									Last updated on {{ guide.last_update }}
								</i>
							</li>
							{% if guide.has_bounty %}
								<li></li>
							{% else %}
								<li></li>
							{% endif %}
						</ul>
					</a>
				</div>
			{% endfor %}
		{% endif %}
	</main>
{% endblock %}