config/urls.py
"""Base URL settings for the Study Buffalo website."""
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.contrib.sitemaps.views import sitemap

from supporting import views
from supporting.sitemaps import PlaySitemap, StudySitemap, ToolSitemap, ReadSitemap, StaticViewSitemap


sitemaps = {
    'play': PlaySitemap('play'),
    'study': StudySitemap('study'),
    'tools': ToolSitemap('tools'),
    'read': ReadSitemap('read'),
    'static': StaticViewSitemap('other'),
}

urlpatterns = [
    path('api/', include('study_buffalo.api.urls', namespace='api')),
    path('play/', include('play.urls')),
    path('study/', include('study.urls')),
    path('read/', include('read.urls')),
    path('tools/', views.tools_index, name='tools_index'),
    path('rdrhc-calendar/', include('rdrhc_calendar.urls', namespace='rdrhc_calendar')),
    path('tools/alberta-adaptations/', views.alberta_adaptations_index, name='alberta_adaptations_index'),
    path('tools/dictionary/', include('dictionary.urls')),
    path('tools/dpd/', include('hc_dpd.urls', namespace='hc_dpd')),
    path('tools/drug-price-calculator/', include('drug_price_calculator.urls')),
    path('tools/substitutions/', include('substitutions.urls')),
    path('tools/vancomycin-calculator/', include('vancomycin_calculator.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('design/', views.design_index, name='design_index'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('robot-policy/', views.robot_policy, name='robot_policy'),
    path('contact/', views.contact, name='contact'),
    path(
        'sitemap/',
        views.custom_sitemap,
        {'sitemaps': sitemaps, 'template_name': 'sitemap_template.html', 'content_type': None},
        name='sitemap'
    ),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('unsubscribe/', views.unsubscribe, name='unsubscribe'),
    path('unsubscribe/complete/', views.unsubscribe_complete, name='unsubscribe_complete'),
    path('accounts/profile/', views.account_profile, name='account_profile'),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt'), name='robots.txt'),
    path('', views.Index.as_view(), name='index'),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TEMPORARY URLS & REDIRECTS
urlpatterns += [
    path('cabs2018/', TemplateView.as_view(template_name='pages/cabs2018.html'), name='cabs2018'),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            '400/',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')},
        ),
        path(
            '403/',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')},
        ),
        path(
            '404/',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')},
        ),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

sb_django/urls.py
"""
Definition of urls for sb_django.
"""
from django.conf.urls import url
import django.contrib.auth.views

from django.conf.urls import include
from django.contrib import admin
from django.views.generic import RedirectView
from . import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from .sitemaps import *

import environ

# Dictionary containing your sitemap classes
sitemaps = {
   "play": PlaySitemap("play"),
   "study": StudySitemap("study"),
   "tools": ToolSitemap("tools"),
   "read": ReadSitemap("read"),
   "static": StaticViewSitemap("other"),
}

urlpatterns = [
    url(r"^play/", include("play.urls")),
    url(r"^study/", include("study.urls")),
    url(r"^read/", include("read.urls")),
    url(r"^tools/$", views.tools_index, name="tools_index"),
    url(r"^tools/alberta-adaptations/", views.alberta_adaptations_index, name="alberta_adaptations_index"),
    url(r"^tools/drug-price-calculator/", include("drug_price_calculator.urls")),
    url(r"^tools/vancomycin-calculator/", include("vancomycin_calculator.urls")),
    url(r"^design/$", views.design_index, name="design_index"),
    url(r"^privacy-policy/", views.privacy_policy, name="privacy_policy"),
    url(r"^robot-policy/", views.robot_policy, name="robot_policy"),
    url(r"^contact/", views.contact, name="contact"),
    url(r"^sitemap/", views.custom_sitemap, {"sitemaps": sitemaps, "template_name": "sitemap_template.html", "content_type": None}, name="sitemap"),
    url(r"^sitemap\.xml$", sitemap, {"sitemaps": sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r"^accounts/profile/$", views.account_profile, name="account_profile"),
    url(r"^accounts/", include("allauth.urls")),
    url(r"^$", views.Index.as_view(), name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Set a secure path for the admin site
# Set the Base Directory
BASE_DIR = environ.Path(__file__) - 2

# Connect to the .env file
env = environ.Env(DEBUG=(bool, False),)
environ.Env.read_env(env_file=BASE_DIR.path('..', 'config').file('studybuffalo.env'))

admin_regex = r"%s" % env('ADMIN_URL')

urlpatterns += [
    url(admin_regex, include(admin.site.urls)),
]

study_buffalo/play/urls.py
"""URLs for the Play app."""
from django.urls import path

from . import views


urlpatterns = [
    path('archive/', views.Archive.as_view(), name='play_archive'),
    path('<int:pk>/', views.PlayPageDetail.as_view(), name='play_page'),
    path('', views.Index.as_view(), name='play_index'),
]

study_buffalo/play/models.py
"""Models for the Play app."""
from datetime import datetime
from io import BytesIO
import uuid

from PIL import Image, ImageFile

from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.urls import reverse
import django.utils.timezone


class Category(models.Model):
    """Defines categories for Play Items"""
    category = models.CharField(
        max_length=100,
        help_text='The name of the category',
    )

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        """String representing the Category object"""
        return self.category


class PlayPage(models.Model):
    """Defines a page to contain PlayItem(s)"""
    title = models.CharField(
        max_length=256,
        help_text='Title for the page',
    )
    date = models.DateField(
        default=django.utils.timezone.now,
        help_text='Date the play item was released',
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        null=True,
    )
    release_date = models.DateTimeField(
        default=django.utils.timezone.now,
        help_text='Date to release this page on',
    )

    class Meta:
        ordering = ['date', 'title']
        verbose_name = 'Page'
        verbose_name_plural = 'Pages'

    def __str__(self):
        """String representing the Play Image object"""
        return f'{self.date} - {self.title}'

    def get_absolute_url(self):
        """Returns the URL to this page"""
        return reverse('play_page', args=[str(self.id)])

    def previous_page(self):
        """Returns the previous primary key ID."""
        previous_pk = self.pk - 1

        if previous_pk > 0:
            return previous_pk

        return None

    def next_page(self):
        """Returns the next primary key ID."""
        if self.last_page() is None:
            return None

        next_pk = self.pk + 1

        if next_pk <= self.last_page():
            return next_pk

        return None

    @staticmethod
    def last_page():
        """Returns the latest released page."""
        latest = PlayPage.objects.filter(
            release_date__date__lte=datetime.now()
        ).order_by(
            'release_date'
        ).last()

        if latest:
            return latest.pk

        return None


class PlayImage(models.Model):
    """Defines an individual image and its characteristics"""
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text='Unqiue ID for this item',
    )
    title = models.CharField(
        max_length=256,
        help_text='Title to display above the image',
        blank=True,
    )
    type = models.CharField(
        max_length=1,
        default='i',
        editable=False,
        help_text='The file type of the item',
    )
    original_image = models.ImageField(
        upload_to='play/images/original/',
        help_text='The uploaded image (high quality)',
    )
    resized_image = models.ImageField(
        upload_to='play/images/resized/',
        editable=False,
    )
    alt_text = models.CharField(
        max_length=256,
        blank=True,
        help_text='Text to show on cursor hover over the item',
    )
    description = models.TextField(
        blank=True,
        help_text='Any additional text to display below the image',
    )
    page = models.ForeignKey(
        'PlayPage',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    ordering = models.PositiveSmallIntegerField(
        default=1,
    )

    class Meta:
        ordering = ['ordering', 'title']
        verbose_name = 'Image'
        verbose_name_plural = 'Images'

    def save(self, *args, **kwargs):
        """Modifies save file functionality to generate a smaller file size"""
        # Fix for truncated image files
        ImageFile.LOAD_TRUNCATED_IMAGES = True

        # Create a lower resolution image (if needed)
        orig = Image.open(self.original_image)

        if orig.width > 800:
            oWidth = orig.width
            oHeight = orig.height
            nWidth = 800
            nHeight = int(round((nWidth / oWidth) * oHeight))

            resize = orig.resize((nWidth, nHeight), Image.Resampling.LANCZOS)
        else:
            resize = orig

        # Reduce dolor depth
        resize_io = BytesIO()
        resize.save(resize_io, format=orig.format, optimize=True)

        # Assign the new resize image to the resized_image field
        self.resized_image.save(self.original_image.name, resize_io, save=False)

        # Save the files
        super().save()

    def __str__(self):
        """String representing the Play Image object"""
        return self.original_image.name or ''


class PlayAudio(models.Model):
    """Defines an individual audio and its characteristics"""
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text='Unqiue ID for this item',
    )
    title = models.CharField(
        max_length=256,
        help_text='Title to display above the audio player',
        blank=True,
    )
    type = models.CharField(
        max_length=1,
        default='a',
        editable=False,
        help_text='The file type of the item',
    )
    audio = models.FileField(
        upload_to='play/audio/',
        help_text='The uploaded audio content',
    )
    description = models.TextField(
        blank=True,
        help_text='Any additional text to display below the image',
    )
    page = models.ForeignKey(
        'PlayPage',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )

    ordering = models.PositiveSmallIntegerField(
        default=1,
    )

    class Meta:
        ordering = ['title']
        verbose_name = 'Audio'
        verbose_name_plural = 'Audio'

    def __str__(self):
        """String representing the Play Audio object"""
        return self.title


@receiver(post_delete, sender=PlayImage)
def play_image_delete(sender, instance, **kwargs):  # pylint: disable=unused-argument
    """Removes the image file on model instance deletion"""
    instance.original_image.delete(False)
    instance.resized_image.delete(False)

study_buffalo/play/views.py
"""Views for the Play app."""
from datetime import datetime

from django.views import generic

from .models import PlayPage


class Index(generic.ListView):
    """Index view for the Play app."""
    context_object_name = 'play_page'
    template_name = 'play/index.html'

    def get_queryset(self):
        return PlayPage.objects.filter(release_date__date__lte=datetime.now()).order_by('-id').first()


class Archive(generic.ListView):
    """Archive view for the Play app."""
    model = PlayPage

    context_object_name = 'play_page_list'


class PlayPageDetail(generic.DetailView):
    """Detail view for a Play item."""
    model = PlayPage

    context_object_name = 'play_page'

study_buffalo/play/templates/play/index.html
{% extends "base_generic.html" %}


{% block content %}
	<h1>Play</h1>

	{% if play_page %}
		<h2>{{ play_page.date|date:"Y.m.d" }} - {{ play_page.title }}</h2>

		{% include "play/playpage_display.html" %}
	{% endif %}
{% endblock %}

study_buffalo/play/templates/play/playpage_detail.html
{% extends "base_generic.html" %}

{% block content %}
	{% if play_page %}
		<h1>
			<a href="{% url 'play_index' %}">Play</a> 
			&gt; {{ play_page.date|date:"Y.m.d" }} - {{ play_page.title}}
		</h1>

		{% include "play/playpage_display.html" %}
	{% endif %}
{% endblock %}

study_buffalo/play/templates/play/playpage_display.html
<style>
  /* TODO: Separate styling for text links and image links */
  #sb h2 {
    text-align: left;
  }

    #sb h2::after {
      content: none;
    }

  #sb main a, #sb main, p {
    text-align: center;
  }

  #sb main a {
    border: 1px solid rgb(200, 200, 200);
    box-shadow: 4px 4px 10px rgb(200, 200, 200);
    display: inline-block;
    margin: 0;
    padding: 5px;
  }

    #sb main a img {
      display: block;
      max-height: 90vh;
    }

  #sb #play-page-nav {
    display: flex;
        flex-direction: row;
        justify-content: center;
        padding: 0;
        margin: 3rem 0;
  }

    #sb #play-page-nav li {
      border-left: 2px solid rgb(101, 101, 101);
      color: rgb(50, 50, 50);
      display: inline-block;
      font-size: 3rem;
      list-style: none;
    }

      #sb #play-page-nav li:first-child {
        border-left: none;
      }

    #sb #play-page-nav a {
      color: inherit;
      display: block;
      padding: 0 3rem;
      text-decoration: none;
      transition: 0.25s ease-in-out;
    }

      #sb #play-page-nav a:hover {
        color: rgb(31, 103, 0) ;
        cursor: pointer;
        transform: scale(1.15);
      }

    #sb #play-page-nav span {
      color: rgb(151, 151, 151);
      cursor: not-allowed;
      display: block;
      padding: 0 3rem;
    }

    @media screen and (max-width: 768px) {
      #sb #play-page-nav {
        align-content: center;
        flex-direction: column;
      }

      #sb #play-page-nav li {
        border-left: none;
        padding: 0.5rem 0;
        text-align: center;
      }

      #sb #play-page-nav a {
        display: inline-block;
      }
    }

    @media screen and (min-width: 768px) and (max-width: 1024px) {
      #sb #play-page-nav li {
        font-size: 2.5rem;
      }

      #sb #play-page-nav a {
        padding: 0 1rem;
      }
    }
</style>

<main>
  {% for item in play_page.playimage_set.all %}
    {% if item.title %}
      <h2>{{ item.title }}</h2>
    {% endif %}

    {% if item.type == "i" %}
      <a href="{{ item.original_image.url }}" target="_blank">
        <img src="{{ item.resized_image.url }}" title="{{ item.alt_text }}">
      </a>
    {% endif %}

    {% if item.description %}
      <p>{{ item.description|safe|linebreaks }}</p>
    {% endif %}
  {% endfor %}

  {% for item in play_page.playaudio_set.all %}
    {% if item.title %}
      <h2>{{ item.title }}</h2>
    {% endif %}

    {% if item.type == "a" %}
      <audio controls src="{{ item.audio.url }}">
        This browser does not support audio playback.
      </audio>
    {% endif %}

    {% if item.description %}
      <p>{{ item.description|safe|linebreaks }}</p>
    {% endif %}
  {% endfor %}
</main>

<nav>
  <ul id="play-page-nav">
    {% if play_page.previous_page %}
      <li><a href="{% url 'play_page' 1 %}">&laquo; First</a></li>
      <li><a href="{% url 'play_page' play_page.previous_page %}">&lsaquo; Previous</a></li>
    {% else %}
      <li><span>&laquo; First</span></li>
      <li><span>&lsaquo; Previous</span></li>
    {% endif %}

      <li><a href="{% url 'play_archive' %}">Archive</a></li>

    {% if play_page.next_page %}
      <li><a href="{% url 'play_page' play_page.next_page %}">Next &rsaquo;</a></li>
      <li><a href="{% url 'play_page' play_page.last_page %}">Last &raquo;</a></li>
    {% else %}
      <li><span>Next &rsaquo;</span></li>
      <li><span>Last &raquo;</span></li>
    {% endif %}
  </ul>
</nav>

study_buffalo/play/templates/play/playpage_list.html
{% extends "base_generic.html" %}

{% load static %}

{% block content %}
	<h1>Play</h1>

	{% if play_page_list %}
		<table>
			<thead>
				<tr>
					<th>Date</th>
					<th>Title</th>
					<th>Category</th>
				</tr>
			</thead>
			<tbody>
				{% for page in play_page_list %}
					<tr>
						<td><a href="{% url 'play_page' page.pk %}">{{ page.date }}</a></td>
						<td><a href="{% url 'play_page' page.pk %}">{{ page.title }}</a></td>
						<td><a href="{% url 'play_page' page.pk %}">{{ page.category }}</a></td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% endif %}
{% endblock %}