config/urls.py
"""Base URL settings for the Study Buffalo website."""
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.contrib.sitemaps.views import sitemap

from supporting import views
from supporting.sitemaps import PlaySitemap, StudySitemap, ToolSitemap, ReadSitemap, StaticViewSitemap


sitemaps = {
    'play': PlaySitemap('play'),
    'study': StudySitemap('study'),
    'tools': ToolSitemap('tools'),
    'read': ReadSitemap('read'),
    'static': StaticViewSitemap('other'),
}

urlpatterns = [
    path('api/', include('study_buffalo.api.urls', namespace='api')),
    path('play/', include('play.urls')),
    path('study/', include('study.urls')),
    path('read/', include('read.urls')),
    path('tools/', views.tools_index, name='tools_index'),
    path('rdrhc-calendar/', include('rdrhc_calendar.urls', namespace='rdrhc_calendar')),
    path('tools/alberta-adaptations/', views.alberta_adaptations_index, name='alberta_adaptations_index'),
    path('tools/dictionary/', include('dictionary.urls')),
    path('tools/dpd/', include('hc_dpd.urls', namespace='hc_dpd')),
    path('tools/drug-price-calculator/', include('drug_price_calculator.urls')),
    path('tools/substitutions/', include('substitutions.urls')),
    path('tools/vancomycin-calculator/', include('vancomycin_calculator.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('design/', views.design_index, name='design_index'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('robot-policy/', views.robot_policy, name='robot_policy'),
    path('contact/', views.contact, name='contact'),
    path(
        'sitemap/',
        views.custom_sitemap,
        {'sitemaps': sitemaps, 'template_name': 'sitemap_template.html', 'content_type': None},
        name='sitemap'
    ),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('unsubscribe/', views.unsubscribe, name='unsubscribe'),
    path('unsubscribe/complete/', views.unsubscribe_complete, name='unsubscribe_complete'),
    path('accounts/profile/', views.account_profile, name='account_profile'),
    path('accounts/', include('allauth.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt'), name='robots.txt'),
    path('', views.Index.as_view(), name='index'),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# TEMPORARY URLS & REDIRECTS
urlpatterns += [
    path('cabs2018/', TemplateView.as_view(template_name='pages/cabs2018.html'), name='cabs2018'),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            '400/',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')},
        ),
        path(
            '403/',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')},
        ),
        path(
            '404/',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')},
        ),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

sb_django/urls.py
"""
Definition of urls for sb_django.
"""
from django.conf.urls import url
import django.contrib.auth.views

from django.conf.urls import include
from django.contrib import admin
from django.views.generic import RedirectView
from . import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from .sitemaps import *

import environ

# Dictionary containing your sitemap classes
sitemaps = {
   "play": PlaySitemap("play"),
   "study": StudySitemap("study"),
   "tools": ToolSitemap("tools"),
   "read": ReadSitemap("read"),
   "static": StaticViewSitemap("other"),
}

urlpatterns = [
    url(r"^play/", include("play.urls")),
    url(r"^study/", include("study.urls")),
    url(r"^read/", include("read.urls")),
    url(r"^tools/$", views.tools_index, name="tools_index"),
    url(r"^tools/alberta-adaptations/", views.alberta_adaptations_index, name="alberta_adaptations_index"),
    url(r"^tools/drug-price-calculator/", include("drug_price_calculator.urls")),
    url(r"^tools/vancomycin-calculator/", include("vancomycin_calculator.urls")),
    url(r"^design/$", views.design_index, name="design_index"),
    url(r"^privacy-policy/", views.privacy_policy, name="privacy_policy"),
    url(r"^robot-policy/", views.robot_policy, name="robot_policy"),
    url(r"^contact/", views.contact, name="contact"),
    url(r"^sitemap/", views.custom_sitemap, {"sitemaps": sitemaps, "template_name": "sitemap_template.html", "content_type": None}, name="sitemap"),
    url(r"^sitemap\.xml$", sitemap, {"sitemaps": sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r"^accounts/profile/$", views.account_profile, name="account_profile"),
    url(r"^accounts/", include("allauth.urls")),
    url(r"^$", views.Index.as_view(), name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Set a secure path for the admin site
# Set the Base Directory
BASE_DIR = environ.Path(__file__) - 2

# Connect to the .env file
env = environ.Env(DEBUG=(bool, False),)
environ.Env.read_env(env_file=BASE_DIR.path('..', 'config').file('studybuffalo.env'))

admin_regex = r"%s" % env('ADMIN_URL')

urlpatterns += [
    url(admin_regex, include(admin.site.urls)),
]

study_buffalo/read/urls.py
"""URLs for the Read app."""
from django.urls import path

from . import views


urlpatterns = [
    path('<int:pk>/', views.PublicationDetail.as_view(), name='pub_page'),
    path('', views.Index.as_view(), name='pub_index'),
]

study_buffalo/read/models.py
"""Models for the Read app."""
from django.db import models
from django.urls import reverse


class Publication(models.Model):
    """Defines the main publication model"""
    title = models.CharField(
        help_text='The title of the study guide',
        max_length=100,
    )
    description = models.CharField(
        help_text='A short description of the study guide',
        max_length=256,
    )
    date_published = models.DateField(
        help_text='The date the first version was released',
    )

    class Meta:
        ordering = ['title']

    def __str__(self):
        return f'{self.date_published} - {self.title}'

    def get_absolute_url(self):
        """Returns the URL to this page"""
        return reverse('pub_page', args=[str(self.id)])


class HTMLPublication(models.Model):
    """Defines an HTML publication"""
    publication = models.ForeignKey(
        'Publication',
        on_delete=models.CASCADE,
    )
    html = models.TextField(
        help_text='The HTML content to display the publication'
    )

    def __str__(self):
        return f'HTML for {self.publication}'


class DocumentPublication(models.Model):
    """Defines a document study guide"""
    publication = models.ForeignKey(
        'Publication',
        on_delete=models.CASCADE,
    )
    document = models.FileField(
        help_text='The publicationfile to upload (PDF preferred)',
        upload_to='publications',
    )

    def __str__(self):
        return f'Document for {self.publication}'

study_buffalo/read/views.py
"""Views for the Read app."""
from django.views import generic
from .models import Publication


class Index(generic.ListView):
    """Index page view for the Read app."""
    model = Publication
    context_object_name = 'pub_list'
    template_name = 'read/index.html'


class PublicationDetail(generic.DetailView):
    """Detail view for a Publication."""
    model = Publication

    context_object_name = 'publication_page'

study_buffalo/read/templates/read/index.html
{% extends "base_generic.html" %}

{% block styles %}
	<style>
		#sb main {
			display: flex;
			flex-direction: column;
			justify-content: center;
			padding: 0;
			margin: 0;
		}

			#sb main .article {
				border: 2px solid rgb(101, 101, 101);
				display: block;
				margin: 1rem 0.2rem;
				transition: 0.25s ease-in-out;
				width: 100%;
			}

				#sb main .article:hover {
					border: 2px solid rgb(41, 138, 0);
				}

					#sb main .article:hover h2 {
						background-color: rgb(41, 138, 0);
					}

				#sb main .article a {
					color: inherit;
					display: block;
					text-decoration: none;
				}

				#sb main .article h2 {
					background-color: rgb(31, 103, 0);
					color: rgb(250, 250, 250);
					display: block;
					padding: 2rem 1rem;
					margin: 0;
					transition: 0.25s ease-in-out;
				}

				#sb main .article h2::after {
					content: none;
				}

				#sb main .article div:nth-child(2) {
					padding: 2rem;
				}

				#sb main .article div:nth-child(3) {
					background-color: rgb(50, 50, 50);
					color: rgb(250, 250, 250);
					display: block;
					font-size: 1.6rem;
					padding: 0.25rem 2rem;
				}
	</style>
{% endblock %}

{% load static %}

{% block content %}
	<h1>Read</h1>

	<main>
		{% if pub_list %}
			{% for pub in pub_list %}
				<div class="article">
					<a href="{% url 'pub_page' pub.pk %}">
						<h2>{{ pub.title }}</h2>

						<div>{{ pub.description }}</div>

						<div>Published on {{ pub.date_published }}</div>
					</a>
				</div>
			{% endfor %}
		{% endif %}
	</main>
{% endblock %}

study_buffalo/read/templates/read/publication_detail.html
{% extends "base_generic.html" %}

{% load static %}

{% block content %}
	{% if publication_page %}
		<h1><a href="{% url 'study_index' %}">Study</a> &gt; {{ publication_page.title }}</h1>
		
		<p>
			<strong>Published:</strong> 
			{{ publication_page.date_published|date:"Y.m.d" }}
		</p>
		{% for item in publication_page.htmlpublication_set.all %}
			<div>{{ item.html|safe }}</div>
		{% endfor %}

		{% for item in publication_page.documentpublication_set.all %}
			<div class="embedded_pdf">
				<object data="{{ item.document.url }}" type="application/pdf">
					<a href="{{ item.document.url }}" target="_blank">
						Sorry, your browser cannot display the Publication - 
						click here to download it
					</a>
				</object>
			</div>
			
			<div class="center_content">
				<a href="{{ item.document.url }}" target="_blank">
					Click here to open this in a new window
				</a>
			</div>
		{% endfor %}
	{% endif %}
{% endblock %}